"""Writers that persist compiled artifacts to disk."""

from __future__ import annotations

import ast
import json
from dataclasses import dataclass
from pathlib import Path

from .jsx_imports import rewrite_pyx_import_specifiers
from .model import CompilationResult, PageMetadata
from .parser import PyxParseResult

_STATIC_STUB = '"""Generated by Pyxle for a static page."""\n'
_JSX_STUB = "// Generated by Pyxle: no client component provided.\n"
_SERVER_IMPORT = "from pyxle.runtime import server"


@dataclass
class ArtifactWriter:
    build_root: Path
    client_root: Path
    server_root: Path
    metadata_root: Path

    def write(
        self,
        source_path: Path,
        page_relative_path: Path,
        route_path: str,
        alternate_route_paths: tuple[str, ...] | None,
        parse_result: PyxParseResult,
    ) -> CompilationResult:
        server_rel = Path("pages") / page_relative_path.with_suffix(".py")
        client_rel = Path("pages") / page_relative_path.with_suffix(".jsx")
        metadata_rel = Path("pages") / page_relative_path.with_suffix(".json")

        server_output = self.server_root / server_rel
        client_output = self.client_root / client_rel
        metadata_output = self.metadata_root / metadata_rel

        server_output.parent.mkdir(parents=True, exist_ok=True)
        client_output.parent.mkdir(parents=True, exist_ok=True)
        metadata_output.parent.mkdir(parents=True, exist_ok=True)

        python_code = (
            parse_result.python_code
            if parse_result.python_code.strip()
            else _STATIC_STUB
        )
        if parse_result.loader and python_code.strip():
            python_code = ensure_server_import(python_code)
        jsx_code = (
            parse_result.jsx_code
            if parse_result.jsx_code.strip()
            else _JSX_STUB
        )
        jsx_code, _ = rewrite_pyx_import_specifiers(jsx_code)

        server_output.write_text(python_code, encoding="utf-8")
        client_output.write_text(jsx_code, encoding="utf-8")

        metadata = PageMetadata(
            route_path=route_path,
            alternate_route_paths=tuple(alternate_route_paths or ()),
            client_path="/" + client_rel.as_posix(),
            server_path="/" + server_rel.as_posix(),
            loader_name=parse_result.loader.name if parse_result.loader else None,
            loader_line=parse_result.loader.line_number if parse_result.loader else None,
            head_elements=parse_result.head_elements,
            head_is_dynamic=parse_result.head_is_dynamic,
        )

        metadata_output.write_text(
            json.dumps(metadata.to_json(), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

        return CompilationResult(
            source_path=source_path,
            python_code=python_code,
            jsx_code=jsx_code,
            server_output=server_output,
            client_output=client_output,
            metadata_output=metadata_output,
            metadata=metadata,
        )


def ensure_server_import(source: str, *, return_insert_position: bool = False) -> str | tuple[str, int | None]:
    if not source.strip():
        return (source, None) if return_insert_position else source

    try:
        module = ast.parse(source, mode="exec", type_comments=True)
    except SyntaxError:  # pragma: no cover - defensive fallback
        module = None

    if module is not None and not _needs_server_import(module):
        return (source, None) if return_insert_position else source

    lines = source.splitlines()
    insert_at = _determine_server_import_index(lines, module)
    lines.insert(insert_at, _SERVER_IMPORT)

    result = "\n".join(lines)
    if source.endswith("\n"):
        result += "\n"
    if return_insert_position:
        return result, insert_at
    return result


def _needs_server_import(module: ast.Module) -> bool:
    for node in module.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == "server":
            return False
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "server":
                    return False
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id == "server":
            return False
        if isinstance(node, ast.ImportFrom):
            for alias in node.names:
                if alias.asname == "server" or (alias.asname is None and alias.name == "server"):
                    return False
        if isinstance(node, ast.Import):
            for alias in node.names:
                name = alias.asname or alias.name.split(".")[-1]
                if name == "server":
                    return False
    return True


def _determine_server_import_index(lines: list[str], module: ast.Module | None) -> int:
    if not lines:
        return 0

    line_after_prelude = _line_after_docstring_and_future(module)
    if line_after_prelude is not None:
        return min(max(line_after_prelude, 0), len(lines))

    index = 0
    while index < len(lines) and not lines[index].strip():
        index += 1
    return index


def _line_after_docstring_and_future(module: ast.Module | None) -> int | None:
    if module is None or not module.body:
        return None

    insert_line = 0
    body_index = 0

    first_stmt = module.body[0]
    if _is_module_docstring(first_stmt):
        insert_line = first_stmt.end_lineno or first_stmt.lineno
        body_index = 1

    while body_index < len(module.body):
        node = module.body[body_index]
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            insert_line = node.end_lineno or node.lineno
            body_index += 1
            continue
        break

    if insert_line == 0:
        return None
    return insert_line


def _is_module_docstring(node: ast.stmt) -> bool:
    return (
        isinstance(node, ast.Expr)
        and isinstance(node.value, ast.Constant)
        and isinstance(node.value.value, str)
        and node.col_offset == 0
    )
